
server:
  #port: 8800
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      #defaultZone: http://eureka-compass1.1d35.starter-us-east-1.openshiftapps.com/eureka/
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: ShoppingService